---
# file: roles/brew/tasks/casks.yml

- include_vars: casks.yml

- name: brew::casks | add HOMEBREW_CASK_OPTS to env
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "export HOMEBREW_CASK_OPTS='--appdir={{ brew_cask_appdir }} --caskroom={{ brew_cask_caskroom }}'"

- name: brew::casks | tap
  homebrew_tap:
    name: "{{ brew_cask_tap_name }}"
    state: present

- name: brew::casks | update
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: brew::casks | install cask
  homebrew:
    name: "{{ brew_cask_formula }}"
    state: present

- name: brew::casks | install apps
  homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items: brew_casks

- name: brew::casks | cleanup
  command: /usr/local/bin/brew cask cleanup
