---
# file: roles/brew/tasks/main.yml

- name: brew | update 1
  homebrew: update_homebrew=yes

- name: brew | tap
  homebrew_tap: name={{ item }} state=present
  with_items: brew_taps

- name: brew | update 2
  homebrew: update_homebrew=yes upgrade_all=yes

- name: brew | install packages
  homebrew: name={{ item }} state=upgraded
  with_items: brew_pkgs

# - name: Check for installed apps
#   shell: brew cask list | grep {{ item }}
#   register: installed_applications
#   with_items: casks
#   ignore_errors: true

# - name: print installed casKs
#   debug: msg="cask apps installed {{ installed_applications.results|map(attribute='stdout') }}"

- name: brew | cask install casks
  homebrew_cask: name={{ item }} state=installed
  with_items: brew_casks
  # when: item not in installed_applications.results|map(attribute='stdout')
