---
# file: roles/brew/tasks/main.yml

# TODO
#   * if a new bash was installed add new path to /etc/shells
#   * edit path in ~/.bash_profile echo export PATH='/usr/local/sbin:$PATH' >> ~/.bash_profile
#   * iterm2
#   * sublime text packages

- name: brew | update 1
  homebrew: update_homebrew=yes

- name: brew | tap
  homebrew_tap: name={{ item }} state=present
  with_items: brew_taps

- name: brew | update 2
  homebrew: update_homebrew=yes upgrade_all=yes

- name: brew | install packages
  homebrew: name={{ item }} state=upgraded
  with_items: brew_pkgs

- name: brew | upgrade preinstalled packages
  homebrew: name={{ item.name }} install_options={{ item.options }} state=upgraded
  with_items: upgrade_pkgs

- name: brew | install gnu packages
  homebrew: name={{ item.name }} install_options={{ item.options }} state=upgraded
  with_items: gnu_pkgs

# - name: Check for installed apps
#   shell: brew cask list | grep {{ item }}
#   register: installed_applications
#   with_items: casks
#   ignore_errors: true

# - name: print installed casks
#   debug: msg="cask apps installed {{ installed_applications.results|map(attribute='stdout') }}"

- name: brew | cask install casks
  homebrew_cask: name={{ item }} state=installed
  with_items: brew_casks
  # when: item not in installed_applications.results|map(attribute='stdout')

- name: brew | linkapps
  command: /usr/local/bin/brew linkapps

- name: brew | cleanup
  command: /usr/local/bin/brew cleanup
