---
# file: roles/brew/tasks/main.yml

- name: update 1
  homebrew:
    update_homebrew: yes

- name: taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: brew_taps

- name: update 2
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: install packages
  homebrew:
    name: "{{ item }}"
    state: upgraded
  with_items: brew_pkgs

- name: linkapps
  command: /usr/local/bin/brew linkapps

- name: cleanup
  command: /usr/local/bin/brew cleanup
