---
# file: roles/brew/tasks/main.yml

- name: brew | update 1
  homebrew:
    update_homebrew: yes

- name: brew | tap
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: brew_taps

- name: brew | update 2
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: brew | install packages
  homebrew:
    name: "{{ item }}"
    state: upgraded
  with_items: brew_pkgs

- include: taps.yml
- include: casks.yml
- include: sysutils.yml

- name: brew | linkapps
  command: /usr/local/bin/brew linkapps

- name: brew | cleanup
  command: /usr/local/bin/brew cleanup
