---
brew_tap_dupes_name: homebrew/dupes
brew_tap_dupes_formulas:
  # - { name: 'apack', options: '' }
  # - { name: 'apple-gcc42', options: '' }
  # - { name: 'awk', options: '' }
  - { name: 'diffstat', options: '' }
  - { name: 'diffutils', options: '' }
  - { name: 'ed', options: 'default-names' }
  - { name: 'expect', options: '' }
  # - { name: 'fetchmail', options: '' }
  - { name: 'file-formula', options: '' }
  # - { name: 'gdb', options: '' } # gdb requires further actions to make it work. See `brew info gdb`
  - { name: 'gpatch', options: '' }
  - { name: 'gperf', options: '' }
  - { name: 'grep', options: 'default-names' }
  - { name: 'groff', options: '' }
  - { name: 'gzip', options: '' }
  # - { name: 'heimdal', options: '' }
  # - { name: 'ibedit', options: '' }
  # - { name: 'ibiconv', options: '' }
  # - { name: 'ibpcap', options: '' }
  - { name: 'less', options: '' }
  - { name: 'm4', options: '' }
  - { name: 'make', options: '' }
  - { name: 'nano', options: '' }
  - { name: 'ncurses', options: '' }
  - { name: 'openldap', options: '' }
  - { name: 'openssh', options: 'with-brewed-openssl' }
  - { name: 'rsync', options: '' }
  # - { name: 'screen', options: '' }
  # - { name: 'sof', options: '' }
  # - { name: 'tcl-tk', options: '' }
  - { name: 'tcpdump', options: '' }
  - { name: 'tidy', options: '' }
  - { name: 'units', options: '' }
  - { name: 'unzip', options: '' }
  - { name: 'whois', options: '' }
  - { name: 'zlib', options: '' }
