---
# file: roles/brew/tasks/main.yml

# TODO
#   * if a new bash was installed add new path to /etc/shells
#   * edit path in ~/.bash_profile echo export PATH='/usr/local/sbin:$PATH' >> ~/.bash_profile
#   * iterm2

- name: upgrade preinstalled packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.options }}"
    state: upgraded
  with_items: brew_sysutils_pkgs

- name: brew | linkapps
  command: /usr/local/bin/brew linkapps

- name: brew | cleanup
  command: /usr/local/bin/brew cleanup
