---
# file: roles/python/defaults/main.yml

pythons:
  - { name: 'python', options: 'enable-framework,with-brewed-openssl' }
  - { name: 'python3', options: 'enable-framework,with-brewed-openssl' }

pip_pkgs:
  - autopep8
  - boto
  # - bpython
  # - Celery
  - coverage
  # - dulwich
  - fabric
  # - flake8
  # - Flask
  - green
  # - hieroglyph
  - httpie
  - jedi
  - jinja2
  # - mercurial
  - mock
  # - nose
  # - pandas
  - paramiko
  # - passlib
  - pep8
  # - pip-tools
  # - psdash
  - pylint
  # - psutil
  - pytest
  # - pythong
  - PyYAML
  # - redis
  - requests
  # - see
  # - sendgrid
  # - six
  - SQLAlchemy
  # - Sphinx
  - testrepository
  - tox
  # - unirest
  # - uWSGI
  - virtualenv
  - virtualenvwrapper
  # - Werkzeug
