---
# file: roles/python/defaults/main.yml

pip_pkgs:
  - autopep8
  - boto
  # - bpython
  - coverage
  # - dulwich
  - fabric
  # - flake8
  - Flask
  - green
  # - hieroglyph
  - httpie
  - jedi
  - jinja2
  # - mercurial
  - mock
  # - nose
  - pandas
  - paramiko
  # - passlib
  - pdb
  - pep8
  - pip-tools
  # - psdash
  - pylint
  # - psutil
  - py.test
  - pytest
  # - pythong
  - PyYAML
  - redis
  - requests
  # - see
  - sendgrid
  # - six
  - SQLAlchemy
  # - Sphinx
  - tox
  # - unirest
  # - uWSGI
  - virtualenv
  - virtualenvwrapper
  # - Werkzeug
