---
# file: roles/python/defaults/main.yml

pip_pkgs:
  - autopep8
  - fabric
  # - Flask
  - jinja2
  - SQLAlchemy
  # - Sphinx
  # - Werkzeug
  - boto
  # - bpython
  # - dulwich
  # - flake8
  - green
  # - hieroglyph
  # - httpie
  # - mercurial
  - mock
  # - nose
  - paramiko
  # - passlib
  - pip-tools
  # - psdash
  - pylint
  # - psutil
  - pytest
  # - pythong
  - PyYAML
  - redis
  - requests
  # - see
  - sendgrid
  # - six
  # - unirest
  # - uWSGI
  - virtualenv
  - virtualenvwrapper
