---
# file: roles/python/defaults/main.yml

pythons:
  - { name: 'python', options: 'enable-framework,with-brewed-openssl' }
  - { name: 'python3', options: 'enable-framework,with-brewed-openssl' }

venv:
  home: "{{ ansible_env.HOME }}/dev/py_projects"
  home_envs: "{{ venv.home }}/ENVS"
  wrapper_path: "/usr/local/bin/virtualenvwrapper.sh"
  pkgs:
    - virtualenv
    - virtualenvwrapper

local_pip_pkgs:
  - autopep8
  - awscli
  - fabric
  - httpie
  - jedi
  - jinja2
  - mercurial
  - paramiko
  - pip-tools
  - PyYAML
  - requests
  - tox

# pip_pkgs:
#   - boto
#   - bpython
#   - Celery
#   - coverage
#   - dulwich
#   - flake8
#   - Flask
#   - green
#   - hieroglyph
#   - httpie
#   - jinja2
#   - mock
#   - nose
#   - pandas
#   - paramiko
#   - passlib
#   - psdash
#   - pylint
#   - psutil
#   - pytest
#   - pythong
#   - PyYAML
#   - redis
#   - rednose
#   - requests
#   - see
#   - sendgrid
#   - six
#   - SQLAlchemy
#   - Sphinx
#   - testrepository
#   - tox
#   - unirest
#   - uWSGI
#   - Werkzeug
