---
# file: roles/sublime-text3/tasks/main.yml

# TODO
#   * move sublime text stuff from bash_profile to a st3 conf
#   * append st3 conf to bash_profile

- name: st3 | taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: st3_brew.taps

- name: st3 | install sublime-text3
  homebrew_cask:
    name: "{{ st3_brew.formula }}"
    state: present

- name: st3 | get Package Control and put in Installed Packages directory
  get_url:
    url: "{{ st3_package_control.url }}"
    dest: "{{ st3_package_control.dest }}"

- name: st3 | create config dir if it does not exist
  file:
    path: "{{ st3_conf.path }}"
    state: directory

- name: st3 | sync this config dir with the fs config dir
  synchronize:
    src: "st3_configs/"
    dest: "{{ st3_conf.path }}"

- name: st3 | remove existing User config dir
  file:
    path: "{{ st3_conf.user_pkg_path }}"
    state: absent

- name: st3 | symlink st3 configs
  file:
    src: "{{ st3_conf.path }}"
    dest: "{{ st3_conf.user_pkg_path }}"
    force: yes
    state: link

- name: st3 | create configs from templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ st3_conf.path }}/{{ item }}"
  with_items: st3_conf.templates

- name: st3 | create projects dir
  file:
    path: "{{ item }}"
    state: directory
  with_items: st3_project_dirs
