---
# file: roles/sublime-text3/tasks/main.yml

# TODO
#   * move sublime text stuff from bash_profile to a st3 conf
#   * append st3 conf to bash_profile
#   * https://sublime.wbond.net/docs/syncing

- name: taps
  homebrew_tap:
   name: "{{ item }}"
   state: present
  with_items: st3_brew_taps

- name: install sublime-text3
  homebrew_cask:
    name: "{{ st3_brew_formula }}"
    state: present

- name: ensure paths exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - st3_conf_installed_pkgs
    - st3_conf_user_pkg_path
    - st3_project_dir

- name: get Package Control and put in Installed Packages directory
  get_url:
    url: "{{ st3_package_control_url }}"
    dest: "{{ st3_package_control_dest }}"

- name: copy user preferences to ST3 user config directory
  copy:
    src: Preferences.sublime-settings
    dest: "{{ st3_conf_user_pkg_path }}"

- name: copy package control preferences to ST3 user config directory
  copy:
    src: Package Control.sublime-settings
    dest: "{{ st3_conf_user_pkg_path }}"
