---
# file: roles/sublime-text3/tasks/main.yml

# TODO
#   * append st3 conf to bash_profile
#   * https://sublime.wbond.net/docs/syncing

- name: st3 | brew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: st3_brew_taps

- name: st3 | install app with brew cask
  homebrew_cask:
    name: "{{ st3_cask_formula }}"
    state: present

- name: st3 | ensure required directories exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ st3_app_lib }}"
    - "{{ st3_app_pkg_installed }}"
    - "{{ st3_app_pkg_user }}"
    - "{{ st3_project_dir }}"

- name: st3 | get Package Control and put in Installed Packages directory
  get_url:
    url: "{{ st3_package_control.url }}"
    dest: "{{ st3_package_control.dest }}"

- name: st3 | sync st3 preferences dir with the fs config dir
  synchronize:
    src: "{{ st3_my_prefs_src }}"
    dest: "{{ ansible_env.HOME }}/tmp/"

- name: st3 | sync st3 preferences dir with the fs config dir
  synchronize:
    src: "{{ st3_my_prefs_src }}"
    dest: "{{ st3_prefs_dir_dest }}"

- name: st3 | remove existing User packages dir
  file:
    path: "{{ st3_app_pkg_user }}"
    state: absent

- name: st3 | symlink st3 preferences
  file:
    src: "{{ st3_prefs_dir_dest }}"
    dest: "{{ st3_app_pkg_user }}"
    force: yes
    state: link

- name: st3 | create preferences from templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ st3_prefs_dir_dest }}/{{ item }}"
  with_items: st3_user_pkg_templates
