---
# file: roles/brew/defaults/main.yml

packages:
  - 'Package Control'
  - 'All Autocomplete'
  - 'Anaconda'
  - 'ApplySyntax'
  - 'AutoFileName'
  - 'BracketHighlighter'
  - 'ColorPicker'
  - 'DocBlockr'
  - 'ExportHtml'
  - 'Fold Python'
  - 'Fold Python Docstrings'
  - 'GenerateUUID'
  - 'GitGutter'
  - 'Glue'
  - 'HexViewer'
  - 'Markdown Preview'
  - 'PackageResourceViewer'
  - 'PlistJsonConverter'
  - 'Python Checker'
  - 'Python PEP8 Autoformat'
  - 'PythonStautsBarShowSymbol'
  - 'PythonTest'
  - 'SideBarEnhancements'
  - 'SublimeCodeIntel'
  - 'SublimeLinter'
  - 'SublimeLinter-annotations'
  - 'SublimeLinter-contrib-perl'
  - 'SublimeLinter-javac'
  - 'SublimeLinter-jsl'
  - 'SublimeLinter-json'
  - 'SublimeLinter-pep8'
  - 'SublimeLinter-pyflakes'
  - 'SublimeLinter-pylint'
  - 'SublimeLinter-pyyaml'
  - 'SublimeLinter-ruby'
  - 'SublimeLinter-xmllint'
  - 'SublimeREPL'
  - 'Tag'
  - 'Terminal'

# "Python Improved",
