---
# file: roles/sublime-text3/defaults/main.yml

st3_lib_base: "~/Library/Application\ Support/Sublime\ Text\ 3"

st3_conf:
  path: "{{ app_configs }}/st3"
  user_pkg_path: "{{ st3_lib_base }}/Packages/User"
  installed_pkgs: "{{ st3_lib_base }}/Installed\ Packages"
  templates:
    - 'Glue.sublime-settings'

st3_brew:
  taps:
    - phinze/cask
    - homebrew/versions
  formula: "sublime-text3"

st3_project_dirs:
  - "~/st3_projects"

st3_package_control:
    url: "https://sublime.wbond.net/Package%20Control.sublime-package"
    dest: "{{ st3_conf.installed_pkgs }}/Package\ Control.sublime-package"
