---
# file: roles/sublime-text3/defaults/main.yml

st3_role_name: "sublime-text3"

# user sys config directory ---------------------------------------------------
st3_cfg_default: "{{ ansible_env.HOME }}/.configs"
st3_sys_conf_dir: "{{ app_configs | default(st3_cfg_default) }}/st3"

# st3 preferences directory ---------------------------------------------------
st3_prefs_dir_dest: "{{ st3_sys_conf_dir }}/st3"
st3_my_prefs_src: "roles/{{ st3_role_name }}/files/my_st3_prefs"

# app lib directory -----------------------------------------------------------
st3_app_lib: "{{ ansible_env.HOME }}/Library/Application\ Support/Sublime\ Text\ 3"

# app package directories -----------------------------------------------------
st3_app_pkg_installed: "{{ st3_app_lib }}/Installed\ Packages"
st3_app_pkg_user: "{{ st3_app_lib }}/Packages/User"

# package templates -----------------------------------------------------------
st3_user_pkg_templates:
  - 'Glue.sublime-settings'

# brew taps -------------------------------------------------------------------
st3_brew_taps:
  - phinze/cask
  - homebrew/versions

# brew/cask formula -----------------------------------------------------------
st3_cask_formula: "sublime-text3"

# directory for project/workspace files ---------------------------------------
st3_project_dir: "{{ ansible_env.HOME }}/st3_projects"

# package control url and package settings path -------------------------------
st3_package_control:
    url: "https://sublime.wbond.net/Package%20Control.sublime-package"
    dest: "{{ st3_app_pkg_installed }}/Package\ Control.sublime-package"

# st3_conf:
#   path: "{{ app_configs }}/st3"
#   user_pkg_path: "{{ st3_lib_base }}/Packages/User"
#   installed_pkgs: "{{ st3_lib_base }}/Installed\ Packages"
#   templates:
#     - 'Glue.sublime-settings'

# st3_brew:
#   taps:
#     - phinze/cask
#     - homebrew/versions
#   formula: "sublime-text3"

# st3_project_dirs:
#   - "~/st3_projects"

# st3_package_control:
#     url: "https://sublime.wbond.net/Package%20Control.sublime-package"
#     dest: "{{ st3_conf.installed_pkgs }}/Package\ Control.sublime-package"
