---
# file: roles/osx-defaults/tasks/main.yml

# - name: osx-defaults | set system config
#   action: shell {{ item }}
#   with_items: sys_conf_defaults

- name: osx-defaults | set system config
  script: ../files/osxdefaults.sh
