---
# file: roles/osx-defaults/tasks/main.yml

# TODO
#   * finish defaults mapping
#   * add tasks to execute all of the settings
#   * add user friendly reference
#   * defaults/main will contain all settings
#   * option to set all variables in vars/main

- name: osx-defaults | set system config
  action: shell {{ item }}
  with_items: sys_conf_defaults


###############################################################################
# Kill affected applications                                                  #
###############################################################################

# for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
#   "Dock" "Finder" "Mail" "Messages" "Safari" "SizeUp" "SystemUIServer" \
#   "Terminal" "Transmission" "Twitter" "iCal"; do
#   killall "${app}" > /dev/null 2>&1
# done
# echo "Done. Note that some of these changes require a logout/restart to take effect."
