---
# file: roles/python/defaults/main.yml

# TODO setup projects

# pip_pkgs:
#   - autopep8
#   - awscli
#   - boto
#   - bpython
#   - celery
#   - click
#   - coverage
#   - django
#   - django-requestlogging
#   - django-rest-swagger
#   - djangorestframework
#   - dulwich
#   - elasticsearch
#   - elasticutils
#   - fabric
#   - flake8
#   - Flask
#   - green
#   - hieroglyph
#   - httpie
#   - jinja2
#   - logstash-formatter
#   - mercurial
#   - mock
#   - nose
#   - pandas
#   - paramiko
#   - passlib
#   - poster
#   - psdash
#   - psutil
#   - pylint
#   - pytest
#   - python-dateutil
#   - pythong
#   - PyYAML
#   - redis
#   - rednose
#   - requests
#   - see
#   - sendgrid
#   - six
#   - Sphinx
#   - SQLAlchemy
#   - swiss-chard
#   - testrepository
#   - thrift
#   - tox
#   - unirest
#   - urllib3
#   - uWSGI
#   - Werkzeug
#   - wsgiref
