---
# file: roles/brew-cask/tasks/main.yml

- name: add HOMEBREW_CASK_OPTS to env
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "export HOMEBREW_CASK_OPTS='--appdir={{ brew_cask_appdir }} --caskroom={{ brew_cask_caskroom }}'"

- name: ensure caskroom path exists
  sudo: yes
  file:
    path: "{{ brew_cask_caskroom }}"
    state: directory
    mode: 0775
    owner: "{{ lookup('env','USER') }}"
    group: "admin"
    recurse: yes

- name: update and upgrade brew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: install brew-cask
  homebrew:
    name: brew-cask
    state: present

- name: install cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items: brew_cask_install_apps

- name: cleanup
  command: /usr/local/bin/brew cask cleanup
