---
# file: roles/python/tasks/main.yml

- name: python |  packages easy_install
  easy_install:
    name: {{ item }}
with_items: easy_install_pkgs

- name: python | install pip packages
  # sudo: yes
  pip:
    name: {{ item }}
  with_items: pip_pkgs
