---
# file: roles/python/tasks/main.yml

# Troubleshooting:
#   * brew un/install python
#   * brew un/install python3
#   * sudo easy_install --upgrade pip
#   * brew un/install ansible

- name: python | install brewed pythons
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.options }}"
    state: upgraded
  with_items: py_pythons

# this messes up system python
# - name: python | brew link
#   command: "brew link --overwrite {{ item.name }}"
#   with_items: pythons

- name: python | brew link py2
  command: "brew link python"

- name: python | brew link py3
  command: "brew link --overwrite python3"

- name: brew | cleanup
  command: brew cleanup

- name: python | upgrade pip and setuptools - py2
  pip:
    name: "{{ item }}"
    state: latest
  with_items: py_pip_upgrade_pkgs

- name: python | upgrade pip and setuptools - py3
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  with_items: py_pip_upgrade_pkgs

- name: python | install pip packages - py2
  pip:
    name: "{{ item }}"
  with_items: py_pip_local_pkgs

- name: python | install pip3 packages - py3
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items: py_pip_local_pkgs

##########################################
# setup virtualenv and virtualenvwrapper
##########################################

- name: virtualenv | ensure workon path exists
  file:
    path: "{{ py_venv_home_envs }}"
    state: directory

- name: virtualenv | install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items: py_venv_pkgs

##########################################
# dot files & other configs
##########################################

- name: copy config files to app config directory
  copy:
    src: "{{ item }}"
    dest: "{{ app_configs }}/.{{ item }}"
  with_items: py_dot_files

- name: create python config loader
  template:
    src: "pyrc.j2"
    dest: "{{ ansible_env.HOME }}/.pyrc"

- name: load pyrc at session start
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "test -f {{ ansible_env.HOME }}/.pyrc && source {{ ansible_env.HOME }}/.pyrc;"
