---
# file: roles/python/tasks/main.yml

# Troubleshooting:
#   * brew un/install python
#   * brew un/install python3
#   * sudo easy_install --upgrade pip
#   * brew un/install ansible

- name: install brewed pythons
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.options }}"
    state: upgraded
  with_items: python_pythons

# this messes up system python
# - name: brew link
#   command: "brew link --overwrite {{ item.name }}"
#   with_items: pythons

- name: brew link py2
  command: brew link python

# - name: brew link py3
#   command: brew link --overwrite python3

- name: cleanup
  command: brew cleanup

- name: upgrade pip setuptools and virtualenv - py2
  pip:
    name: "{{ item }}"
    state: present
    extra_args: '--upgrade'
  with_items:
    - pip
    - virtualenv

# - name: upgrade pip and setuptools - py3
#   pip:
#     name: "{{ item }}"
#     state: latest
#     executable: pip3
#     extra_args: '--upgrade'
#   with_items: python_pip_upgrade_pkgs

- name: install pip packages - py2
  pip:
    name: "{{ item }}"
  with_items: python_pip_local_pkgs

- name: install pip3 packages - py3
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items: python_pip_local_pkgs

##########################################
# setup virtualenv and virtualenvwrapper
##########################################

- name: ensure virtualenv workon path exists
  file:
    path: "{{ python_venv_home_envs }}"
    state: directory

- name: install virtualenv pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items: python_venv_pkgs
