#!/bin/bash

###############################
# bash aliases
# used a lot from:
#   https://github.com/mitchellh/dotfiles/blob/master/bashrc
#   http://natelandau.com/my-mac-osx-bash_profile/
###############################

#-------------------------------------------------------------------------------
# Aliases / Functions
#-------------------------------------------------------------------------------
alias cp='cp -v'                           # Preferred 'cp' implementation
alias mv='mv -v'                           # Preferred 'mv' implementation
alias mkdir='mkdir -pv'                     # Preferred 'mkdir' implementation

alias ll='ls -FGlAhp'                       # Preferred 'ls' implementation
alias ls='ls -FGa'
# tree listing
alias lr='ls -R | grep ":$" | sed -e '\''s/:$//'\'' -e '\''s/[^-][^\/]*\//--/g'\'' -e '\''s/^/   /'\'' -e '\''s/-/|/'\'' | less'

alias less='less -FSRXc'                    # Preferred 'less' implementation
alias cd..='cd ../'                         # Go back 1 directory level (for fast typers)
alias ..='cd ../'                           # Go back 1 directory level
alias ...='cd ../../'                       # Go back 2 directory levels
alias .3='cd ../../../'                     # Go back 3 directory levels
alias .4='cd ../../../../'                  # Go back 4 directory levels
alias .5='cd ../../../../../'               # Go back 5 directory levels
alias .6='cd ../../../../../../'            # Go back 6 directory levels
alias f='open -a Finder ./'                 # f:            Opens current directory in MacOS Finder
alias ~="cd ~"                              # ~:            Go Home
alias c='clear'                             # c:            Clear terminal display
alias which='type -all'                     # which:        Find executables
alias path='echo -e ${PATH//:/\\n}'         # path:         Echo all executable Paths
alias show_options='shopt'                  # Show_options: display bash options settings
alias fix_stty='stty sane'                  # fix_stty:     Restore terminal settings when screwed up
alias cic='set completion-ignore-case On'   # cic:          Make tab-completion case-insensitive
alias DT='tee ~/Desktop/terminalOut.txt'    # DT:           Pipe content to file on MacOS Desktop
alias dul='du -h --max-depth=1'
alias hi='history | tail -20'

alias dgits='diff -x .git -x __pycache__ -x *.pyc -x *.coverage -rq'
alias grepr='grep -Hrn'

#---------------------------
# GIT
#---------------------------
alias ga='git add'
alias gc='git commit'
alias gcl='git clone'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gdiff='git diff'
alias gl='git log --pretty=oneline -n 20 --graph --abbrev-commit'
alias gp='git push'
alias gs='git status -s'
alias gt='git tag'

#---------------------------
# FIND
#---------------------------
alias rmds="find . -type f -name '*.DS_Store' -ls -delete" # remove mac droppings
alias finderShowHidden='defaults write com.apple.finder ShowAllFiles TRUE'
alias finderHideHidden='defaults write com.apple.finder ShowAllFiles FALSE'
# qfind:    Quickly search for file
alias qfind="find . -name "

#---------------------------
# MEMORY
#---------------------------
#   memHogsTop, memHogsPs:  Find memory hogs
alias memHogsTop='top -l 1 -o rsize | head -20'
alias memHogsPs='ps wwaxm -o pid,stat,vsize,rss,time,command | head -5'

#   cpuHogs:  Find CPU hogs
alias cpu_hogs='ps wwaxr -o pid,stat,%cpu,time,command | head -10'

# update top every 10 sec
alias ftop='top -l 9999999 -s 10 -o cpu'
#   ttop:  Recommended 'top' invocation to minimize resources
alias ttop="top -R -F -s 10 -o rsize"

#---------------------------
# NETWORKING
#---------------------------
alias myip='curl ip.appspot.com'                    # myip:         Public facing IP Address
alias netCons='lsof -i'                             # netCons:      Show all open TCP/IP sockets
alias flushDNS='dscacheutil -flushcache'            # flushDNS:     Flush out the DNS Cache
alias lsock='sudo /usr/sbin/lsof -i -P'             # lsock:        Display open sockets
alias lsockU='sudo /usr/sbin/lsof -nP | grep UDP'   # lsockU:       Display only open UDP sockets
alias lsockT='sudo /usr/sbin/lsof -nP | grep TCP'   # lsockT:       Display only open TCP sockets
alias ipInfo0='ipconfig getpacket en0'              # ipInfo0:      Get info on connections for en0
alias ipInfo1='ipconfig getpacket en1'              # ipInfo1:      Get info on connections for en1
alias openPorts='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections
alias showBlocked='sudo ipfw list'                  # showBlocked:  All ipfw rules inc/ blocked IPs

#---------------------------
# PYTHON
#---------------------------
alias rmpyc="find . -name '*.pyc' -exec rm '{}' ';'"
alias djm="python manage.py"
alias djrun="python manage.py runserver"
alias djtest="python manage.py test"
alias dgits='diff -x .git -x __pycache__ -x *.pyc -x *.coverage -rq'
alias autopep8-agg='autopep8 --in-place --aggressive --aggressive'
alias unittest='python -m unittest -vvvv'

#---------------------------
# Databases
#---------------------------

alias sqldev='sh ${HOME}/Applications/SQLDeveloper.app/Contents/MacOS/sqldeveloper.sh'

if [[ -d '/usr/local/var/postgres' ]]; then
    alias pg-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
    alias pg-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
fi

#---------------------------
# Brew - gapple/services
# http://robots.thoughtbot.com/starting-and-stopping-background-services-with-homebrew
#---------------------------
alias srv:restart='brew services restart'
alias srv:stop='brew services stop'
alias srv:start='brew services start'
alias srv:list='brew services list'

#---------------------------
# OTHERS
#---------------------------
alias be='bundle exec'
alias v='vagrant'

alias numFiles='echo $(ls -1 | wc -l)'      # numFiles:     Count of non-hidden files in current dir
alias make1mb='mkfile 1m ./1MB.dat'         # make1mb:      Creates a file of 1mb size (all zeros)
alias make5mb='mkfile 5m ./5MB.dat'         # make5mb:      Creates a file of 5mb size (all zeros)
alias make10mb='mkfile 10m ./10MB.dat'      # make10mb:     Creates a file of 10mb size (all zeros)

alias resess="source ${HOME}/.bash_profile"

alias mountReadWrite='/sbin/mount -uw /'    # mountReadWrite:   For use when booted into single-user
alias keycp="cat ${HOME}/.ssh/id_rsa.pub | pbcopy && echo 'Copied to clipboard.'"
alias phpspec='vendor/bin/phpspec'

alias hello='cowsay hi'
alias bye='cowsay good-bye'
alias ghost='printf "\n༼ つ ◕_◕ ༽つ\n"'

alias ibook='open -a iBooks'
alias preview='open -a Preview'

alias dirsize='du -hs */*'
