#!/bin/bash

###############################
# My bash profile
# used a lot from:
#   https://github.com/mitchellh/dotfiles/blob/master/bashrc
#   http://natelandau.com/my-mac-osx-bash_profile/
###############################

#-------------------------------------------------------------------------------
# Basics
#-------------------------------------------------------------------------------
: ${HOME=~}
: ${LOGNAME=$(id -un)}
: ${UNAME=$(uname)}

# Complete hostnames from this file
: ${HOSTFILE=~/.ssh/known_hosts}

#-------------------------------------------------------------------------------
# Shell Options
#-------------------------------------------------------------------------------
shopt -s histappend
test -r /etc/bash.bashrc && . /etc/bash.bashrc

set -o notify
unset MAILCHECK
umask 0022

# Terminal type
case $UNAME in
    CYGWIN* | MINGW32*)
        export TERM=cygwin
        ;;
    *)
        export TERM=xterm-256color
        ;;
esac

#-------------------------------------------------------------------------------
# PATH
#-------------------------------------------------------------------------------
test -f "${HOME}/.profile" && source ${HOME}/.profile
test -f "${HOME}/.bash_aliases" && source ${HOME}/.bash_aliases
test -f "${HOME}/.bashrc" && source ${HOME}/.bashrc

# ~/bin if it exists - want this checked first
test -d "${HOME}/bin" && PATH="${HOME}/bin:${PATH}"

export PATH="/usr/local/bin:${PATH}"

#-------------------------------------------------------------------------------
# Env Configuration
#-------------------------------------------------------------------------------

# detect interactive shell
case "$-" in
    *i*) INTERACTIVE=yes ;;
    *)   unset INTERACTIVE ;;
esac

# detect login shell
case "$0" in
    -*) LOGIN=yes ;;
    *)  unset LOGIN ;;
esac

# Proper locale
: ${LANG:="en_US.UTF-8"}
: ${LANGUAGE:="en"}
: ${LC_CTYPE:="en_US.UTF-8"}
: ${LC_ALL:="en_US.UTF-8"}
export LANG LANGUAGE LC_CTYPE LC_ALL

# Always use passive mode FTP
: ${FTP_PASSIVE:=1}
export FTP_PASSIVE

# Ignore backups, CVS directories
FIGNORE="~:CVS:#:.pyc"
HISTCONTROL=ignoreboth
export HISTFILESIZE=5000

#-------------------------------------------------------------------------------
# Editor and Pager
#-------------------------------------------------------------------------------
EDITOR="vim"
export EDITOR

PAGER="less -FirSwX"
MANPAGER="$PAGER"
export PAGER MANPAGER

#-------------------------------------------------------------------------------
# BREW
#-------------------------------------------------------------------------------

mytmp=$(brew --prefix coreutils)
if [[ -d mytmp ]]; then
    test -d "${mytmp}/libexec/gnuman" &&
        export MANPATH="${mytmp}/libexec/gnuman:${MANPATH}"

    test -d "${mytmp}/libexec/gnubin" &&
        export PATH="${mytmp}/libexec/gnubin:${PATH}"
fi

 test -d '/usr/local/sbin' &&
     export PATH="/usr/local/sbin:${PATH}"

#-------------------------------------------------------------------------------
# User Shell Environment
#-------------------------------------------------------------------------------

# load profile extensions
for profileext in 'functions' 'colors' 'prompt'; do
    test -f "${HOME}/.bash_profile_${profileext}" && source ${HOME}/.bash_profile_${profileext};
done

# load custom functions
for dotfile in 'venv_wrapper' 'mkpystuff' 'st3'; do
    test -f "${HOME}/.${dotfile}" && source ${HOME}/.${dotfile};
done

case $UNAME in
    MINGW32*)
        # Don't condense path, since function doesn't work here.
        ;;
    *)
        # Condense path variables
        PATH=$(puniq $PATH)
        MANPATH=$(puniq $MANPATH)
        ;;
esac

export PATH=".:${HOME}/.node_modules_global/bin:${PATH}"
export NODE_PATH="${NODE_PATH}:${HOME}/.node_modules_global/bin:${HOME}/.node_modules_global/lib/node_modules"
