#!/bin/bash
#-------------------------------------------------------------------------------
# Colors / Formatting
#-------------------------------------------------------------------------------
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
# https://wiki.archlinux.org/index.php/Color_Bash_Prompt

# Reset
PS_CLEAR='\[\033[0m\]'

BOLD='\[\033[1m\]'
UL='\[\033[4m\]'
BLINK='\[\033[5m\]'
DIM='\[\033[2m\]'
INVERTED='\[\033[7m\]'
HIDDEN='\[\033[8m\]'

# Regular Colors
BLACK='\[\e[0;30m\]'
RED='\[\e[0;31m\]'
GREEN='\[\e[0;32m\]'
YELLOW='\[\e[0;33m\]'
BLUE='\[\e[0;34m\]'
PURPLE='\[\e[0;35m\]'
CYAN='\[\e[0;36m\]'
WHITE='\[\e[0;37m\]'

# Bold
B_BLACK='\[\e[1;30m\]'
B_RED='\[\e[1;31m\]'
B_GREEN='\[\e[1;32m\]'
B_YELLOW='\[\e[1;33m\]'
B_BLUE='\[\e[1;34m\]'
B_PURPLE='\[\e[1;35m\]'
B_CYAN='\[\e[1;36m\]'
B_WHITE='\[\e[1;37m\]'

# Underline
U_BLACK='\[\e[4;30m\]'
U_RED='\[\e[4;31m\]'
U_GREEN='\[\e[4;32m\]'
U_YELLOW='\[\e[4;33m\]'
U_BLUE='\[\e[4;34m\]'
U_PURPLE='\[\e[4;35m\]'
U_CYAN='\[\e[4;36m\]'
U_WHITE='\[\e[4;37m\]'

# Background
ON_BLACK='\[\e[40m\]'
ON_RED='\[\e[41m\]'
ON_GREEN='\[\e[42m\]'
ON_YELLOW='\[\e[43m\]'
ON_BLUE='\[\e[44m\]'
ON_PURPLE='\[\e[45m\]'
ON_CYAN='\[\e[46m\]'
ON_WHITE='\[\e[47m\]'

# High Intensity
I_BLACK='\[\e[0;90m\]'
I_RED='\[\e[0;91m\]'
I_GREEN='\[\e[0;92m\]'
I_YELLOW='\[\e[0;93m\]'
I_BLUE='\[\e[0;94m\]'
I_PURPLE='\[\e[0;95m\]'
I_CYAN='\[\e[0;96m\]'
I_WHITE='\[\e[0;97m\]'

# Bold High Intensity
BI_BLACK='\[\e[1;90m\]'
BI_RED='\[\e[1;91m\]'
BI_GREEN='\[\e[1;92m\]'
BI_YELLOW='\[\e[1;93m\]'
BI_BLUE='\[\e[1;94m\]'
BI_PURPLE='\[\e[1;95m\]'
BI_CYAN='\[\e[1;96m\]'
BI_WHITE='\[\e[1;97m\]'

# High Intensity backgrounds
ON_IBLACK='\[\e[0;100m\]'
ON_IRED='\[\e[0;101m\]'
ON_IGREEN='\[\e[0;102m\]'
ON_IYELLOW='\[\e[0;103m\]'
ON_IBLUE='\[\e[0;104m\]'
ON_IPURPLE='\[\e[0;105m\]'
ON_ICYAN='\[\e[0;106m\]'
ON_IWHITE='\[\e[0;107m\]'
