#!/bin/bash

# TODO py-ify and ansible-fy this
#       append source .mypystuff to .bash_profile

function get_st3_prj_file() {
    printf "${ST3_PROJECTS}/${@}.sublime-project"
}

function mkst3prj() {
    prj=$@
    st3prj=$(get_st3_prj_file ${prj})
    # what if project file exists?
    if [[ -f ${st3prj} ]]; then
        echo "project file already exists: [${st3prj}]";
        return 0;
    fi

    # TODO convert this to a template
    cat > $st3prj <<EOL
{
    "build_systems":
    [
        {
            "name": "Anaconda Python Builder",
            "selector": "source.python",
            "shell_cmd": "python -u \"$file\""
        }
    ],
    "folders":
    [
        {
            "name": "${prj} - source",
            "follow_symlinks": true,
            "path": "${PROJECT_HOME}/${prj}"
        },
        {
            "name": "${prj} - env",
            "follow_symlinks": true,
            "path": "${WORKON_HOME}/${prj}"
        }
    ],
    "settings":
    {
        "anaconda_debug": true,
        "anaconda_linter_underlines": true,
        "python_interpreter": "${WORKON_HOME}/${prj}/bin/python",
        "pep257_ignore":
        [
            "D209",
            "D200",
            "D400",
            "D401",
            "D205"
        ],
        "pep8_ignore":
        [
            "E261",
            "E265",
            "E501"
        ],
        "AdvancedNewFile": {
            "base": "${PROJECT_HOME}/${prj}",
            "main": "${PROJECT_HOME}/${prj}/${prj}"
        }
    }
}
EOL
    echo "cat ${st3prj}"
}

function mkpy() {
    myprj=$@
    if [[ $(mkst3prj $myprj) ]]; then
        mkproject $myprj
        subl --project "$(get_st3_prj_file $myprj)"
    fi
}
