#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Sublime Text 3
#-------------------------------------------------------------------------------

# TODO
#   sublp projectname autocomplete
#   subls count projects
#   subls search projects
#   subls find in project

export ST3_PROJECTS="${HOME}/sublime_projects"

[[ ! -d $ST3_PROJECTS ]] && mkdir -p $ST3_PROJECTS

# `s` with no arguments opens the current directory in Sublime Text, otherwise
# opens the given location
function s() {
    if [ $# -eq 0 ]; then
        subl .;
    else
        subl "$@";
    fi;
}

# open project
function sublp () {
    subl --project "${ST3_PROJECTS}/${@}.sublime-project";
}

# list projects
alias subls="find ${ST3_PROJECTS} -name \*.sublime-project -type f | sed 's|'\"${ST3_PROJECTS}\"'/\(.*\).sublime-project|\1|' | column -c 80"

# Opens any file in sublime editor
alias edit='subl'
