#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Sublime Text 3
#-------------------------------------------------------------------------------

# TODO make this a template in st3 role

export ST3_PROJECTS="${HOME}/sublime_projects"

[[ ! -d $ST3_PROJECTS ]] && mkdir -p $ST3_PROJECTS

# open project
sublp () {
    subl --project "${ST3_PROJECTS}/${@}.sublime-project";
}

# list projects
alias subls="find ${ST3_PROJECTS} -name \*.sublime-project -type f | sed 's|'\"${ST3_PROJECTS}\"'/\(.*\).sublime-project|\1|' | column -c 80"
