#!/bin/bash

export PROJECT_HOME="${HOME}/dev"
export WORKON_HOME="${PROJECT_HOME}/ENVS"

[[ ! -d $WORKON_HOME  ]] && mkdir -p $WORKON_HOME
[[ ! -d $PROJECT_HOME  ]] && mkdir -p $PROJECT_HOME

source /usr/local/bin/virtualenvwrapper.sh

alias venv="workon"
alias venv.exit="deactivate"
alias venv.ls="lsvirtualenv"
alias venv.show="showvirtualenv"
alias venv.init="mkvirtualenv"
alias venv.rm="rmvirtualenv"
alias venv.switch="workon"
alias venv.add="add2virtualenv"
alias venv.cd="cdproject"
alias venv.cdsp="cdsitepackages"
alias venv.cdenv="cdvirtualenv"
alias venv.lssp="lssitepackages"
alias venv.proj="mkproject"
alias venv.setproj="setvirtualenvproject"
alias venv.wipe="wipeenv"


function venv.cmds () {
    echo 'venv: workon'
    echo 'venv.exit: deactivate'
    echo 'venv.ls: lsvirtualenv'
    echo 'venv.show: showvirtualenv'
    echo 'venv.init: mkvirtualenv'
    echo 'venv.rm: rmvirtualenv'
    echo 'venv.switch: workon'
    echo 'venv.add: add2virtualenv'
    echo 'venv.cd: cdproject'
    echo 'venv.cdsp: cdsitepackages'
    echo 'venv.cdenv: cdvirtualenv'
    echo 'venv.lssp: lssitepackages'
    echo 'venv.proj: mkproject'
    echo 'venv.setproj: setvirtualenvproject'
    echo 'venv.wipe: wipeenv'
}
