#!/bin/bash

# TODO py-ify and ansible-fy this
#       append source .mypystuff to .bash_profile

function get_st3_prj_file() {
    printf "${HOME}/sublime_projects/${@}.sublime-project"
}

function mkst3prj() {
    prj=$@
    st3prj=$(get_st3_prj_file ${prj})
    # what if project file exists?
    if [[ -f $st3prj ]]; then
        echo "project file already exists: [${st3prj}]";
        return 0;
    fi

    # TODO convert this to a template
    cat > $st3prj <<EOF
{
    "folders":
    [
        {
            "name": "${prj} - source",
            "follow_symlinks": true,
            "path": "${PROJECT_HOME}/${prj}"
        },
        {
            "name": "${prj} - env",
            "follow_symlinks": true,
            "path": "${WORKON_HOME}/${prj}"
        }
    ]
}
EOF
    echo "cat ${st3prj}"
}

function mkpy() {
    myprj=$@
    # TODO confirm project name is valid

    if [[ $(mkst3prj $myprj) ]]; then
        mkproject $myprj
        subl --project "$(get_st3_prj_file $myprj)"
    fi
}
